export const PROJECTS = [
  {
    id: 1,
    title: "Portfolio",
    category: "Next.js Application",
    image: "/images/profile.png",
    description:
      "My personal portfolio website built with Next.js 15 and App Router.",
    technologies: ["Next.js", "TypeScript", "Framer Motion", "Tailwind CSS"],
    liveUrl: "#",
    githubUrl: "https://github.com/moppiiiii/portfolio",
  },
  {
    id: 2,
    title: "React Gantt Flow",
    category: "Component Library",
    image:
      "/placeholder.svg?height=600&width=800&query=react component library storybook",
    description: "Gantt chart library that can display lightning bolt lines",
    technologies: [
      "React",
      "TypeScript",
      "Storybook",
      "Chromatic",
      "SVG Component",
    ],
    liveUrl: "https://main--67923016a18edbfb58483060.chromatic.com/",
    githubUrl: "https://github.com/moppiiiii/react-gantt-flow",
  },
  {
    id: 3,
    title: "kaeruyo",
    category: "Next.js Application",
    image: "/placeholder-vko96.png",
    description: "Schedule sharing application with family members",
    technologies: [
      "Next.js",
      "TypeScript",
      "Shadcn/UI",
      "zod",
      "zustand",
      "supabase",
      "prisma",
    ],
    liveUrl: "",
    githubUrl: "https://github.com/moppiiiii/kaeruyo",
  },
  {
    id: 4,
    title: "Bio Build",
    category: "Next.js Application",
    image: "/images/profile.png",
    description: "Muscle Training and Daily Record",
    technologies: [
      "Next.js",
      "TypeScript",
      "Shadcn/UI",
      "zod",
      "zustand",
      "supabase",
      "prisma",
    ],
    liveUrl: "",
    githubUrl: "https://github.com/moppiiiii/bio-build",
  }
];
